// Anlam → emoji eşleyici. Kelimenin İngilizcesi + Türkçe anlamı taranır,
// ilk eşleşen kural kazanır. Amaç: görseli görünce anlamı hatırlamak.
// Kurallar kabaca "somuttan soyuta" ve "özelden genele" sıralı.

type Rule = [RegExp, string]

const RULES: Rule[] = [
  // — Uzay / gökyüzü —
  [/\b(celest|astro|galax|cosmic|cosmos|gök|gezegen|planet|orbit|yörünge|nebula)/i, '🌌'],
  [/\b(star|yıldız|stellar)/i, '⭐'],
  [/\b(sun|solar|güneş)/i, '☀️'],
  [/\b(moon|lunar|\bay\b)/i, '🌙'],
  [/\b(satellite|uydu|spacecraft|rocket|roket|space ?craft)/i, '🛰️'],
  [/\b(gravity|çekim|yer ?çekimi)/i, '🪐'],
  // — Su / hava / iklim —
  [/\b(water|ocean|\bsea\b|deniz|okyanus|aqua|sıvı|liquid|\bnem\b|moist|ıslak|\bsu\b)/i, '💧'],
  [/\b(rain|yağmur|yağış|precipit)/i, '🌧️'],
  [/\b(flood|sel|taşkın|inundat)/i, '🌊'],
  [/\b(drought|kurak|çöl|desert|barren|arid)/i, '🏜️'],
  [/\b(ice|buz|glacier|buzul|frozen|freeze|don(ma|mak)|frost)/i, '🧊'],
  [/\b(snow|kar\b|kış|winter)/i, '❄️'],
  [/\b(cold|soğuk|chill|serin)/i, '🥶'],
  [/\b(fire|ateş|yangın|burn|yan(mak|ma)|combust|flame|alev|ignit|tutuş)/i, '🔥'],
  [/\b(heat|ısı|sıcak(lık)?|warm|temperatur|derece|thermal)/i, '🌡️'],
  [/\b(wind|rüzgar|breeze|esinti|gale)/i, '🌬️'],
  [/\b(storm|fırtına|hurricane|kasırga|typhoon|tornado|hortum)/i, '🌪️'],
  [/\b(cloud|bulut)/i, '☁️'],
  [/\b(air|hava|atmospher|oxygen|oksijen|gas|gaz|breath|nefes|solunum|akciğer|lung)/i, '💨'],
  [/\b(climate|iklim|weather|meteor)/i, '🌦️'],
  [/\b(lightning|şimşek|yıldırım|thunder|gök ?gürül)/i, '🌩️'],
  // — Yer / doğa —
  [/\b(earth|dünya|yerküre|globe|küresel)/i, '🌍'],
  [/\b(soil|toprak|ground|land|arazi|kara\b|terrain)/i, '🟫'],
  [/\b(mountain|dağ|peak|zirve|highland)/i, '⛰️'],
  [/\b(rock|kaya|stone|taş|boulder|mineral|maden|ore|cevher)/i, '🪨'],
  [/\b(volcano|yanardağ|eruption|püskür|lava|lav\b|magma)/i, '🌋'],
  [/\b(earthquake|deprem|sismik|seismic|tremor|sarsıntı)/i, '🫨'],
  [/\b(island|ada\b|peninsula|yarımada|coast|kıyı|sahil|shore)/i, '🏝️'],
  [/\b(cave|mağara|tunnel|tünel|underground|yer ?altı)/i, '🕳️'],
  [/\b(river|nehir|ırmak|stream|akarsu|lake|göl\b)/i, '🏞️'],
  // — Bitki / tarım —
  [/\b(plant|bitki|vegetat|flora|botan)/i, '🌿'],
  [/\b(tree|ağaç|forest|orman|wood(land)?|jungle|orman)/i, '🌳'],
  [/\b(leaf|leaves|yaprak|foliage)/i, '🍃'],
  [/\b(flower|çiçek|blossom|bloom|açan)/i, '🌸'],
  [/\b(seed|tohum|grain|tahıl|crop|ürün|ekin|harvest|hasat|wheat|buğday)/i, '🌾'],
  [/\b(agricult|tarım|farm|çiftlik|cultivat|ekim|yetiştir)/i, '🚜'],
  [/\b(root|kök\b|köken)/i, '🌱'],
  [/\b(fruit|meyve|berry|çilek)/i, '🍓'],
  // — Hayvanlar —
  [/\b(animal|hayvan|fauna|creature|canlı|beast|memeli|mammal)/i, '🐾'],
  [/\b(species|tür\b|cins)/i, '🦎'],
  [/\b(bird|kuş|avian|kanat|wing|tüy|feather)/i, '🐦'],
  [/\b(fish|balık|marine|denizel|deniz ?canlı)/i, '🐟'],
  [/\b(insect|böcek|larva|kurtçuk)/i, '🐛'],
  [/\b(bee|arı\b|hive|kovan)/i, '🐝'],
  [/\b(ant|karınca)/i, '🐜'],
  [/\b(butterfly|kelebek)/i, '🦋'],
  [/\b(whale|balina|dolphin|yunus)/i, '🐋'],
  [/\b(predator|yırtıcı|avcı\b|prey|av\b)/i, '🦁'],
  [/\b(reptile|sürüngen|snake|yılan)/i, '🐍'],
  [/\b(dinosaur|dinozor|fossil|fosil)/i, '🦕'],
  // — Vücut / sağlık / biyoloji —
  [/\b(bacteri|virus|virüs|microb|mikrop|patho|germ|enfeksiyon|infect|bulaş|contag)/i, '🦠'],
  [/\b(\bdna\b|\bgen\b|genetic|genom|kalıtım|herit|chromosom|kromozom|mutat)/i, '🧬'],
  [/\b(cell|hücre|tissue|doku|membrane|zar\b|organ\b)/i, '🔬'],
  [/\b(brain|beyin|neuro|sinir|nöron|nöro|zihin|cognit|biliş|mental|akıl)/i, '🧠'],
  [/\b(heart|kalp|kardiy|cardiac|nabız|pulse)/i, '❤️'],
  [/\b(blood|kan\b|damar|vessel|vein|toplardamar|arter|kılcal)/i, '🩸'],
  [/\b(bone|kemik|iskelet|skeleton|joint|eklem)/i, '🦴'],
  [/\b(muscle|kas\b|adale)/i, '💪'],
  [/\b(skin|deri|cilt|epiderm)/i, '🖐️'],
  [/\b(eye|göz|vision|görme|görü|sight|optik|optic|retina)/i, '👁️'],
  [/\b(ear|kulak|hearing|işitme|duyma|acoustic|ses ?dalga)/i, '👂'],
  [/\b(tooth|teeth|diş\b|dental)/i, '🦷'],
  [/\b(disease|hastalık|illness|sick|hasta\b|syndrome|sendrom|symptom|belirti|semptom|ache|ağrı|pain)/i, '🤒'],
  [/\b(medic|ilaç|drug|tedavi|treat|cure|iyileş|therapy|terapi|remedy|şifa)/i, '💊'],
  [/\b(vaccine|aşı|immun|bağışık|antibod|antikor)/i, '💉'],
  [/\b(doctor|doktor|hospital|hastane|clinic|klinik|surgery|ameliyat|cerrah|nurse|hemşire)/i, '🩺'],
  [/\b(pregnan|hamile|gebe|birth|doğum|embryo|embriyo|fetus|cenin|offspring|yavru|döl)/i, '🤰'],
  [/\b(death|ölüm|die\b|öl(mek|üm)|mortal|fatal|ölümcül|deadly|lethal)/i, '💀'],
  [/\b(food|yiyecek|gıda|besin|nutri|beslenme|eat|ye(mek|me)\b|diet|diyet|meal|öğün)/i, '🍎'],
  [/\b(hunger|açlık|starve|aç ?kal|famine|kıtlık)/i, '🍽️'],
  // — Kimya / fizik / enerji —
  [/\b(atom|molecul|molekül|element|kimya|chemical|reaction|tepkime|reaksiyon|compound|bileşik|asit|acid|alkali)/i, '⚗️'],
  [/\b(energy|enerji|power|güç\b|kinetic|potansiyel)/i, '⚡'],
  [/\b(electric|elektrik|voltage|volt|akım|current|circuit|devre|charge|yük\b)/i, '🔌'],
  [/\b(magnet|mıknatıs|manyetik)/i, '🧲'],
  [/\b(radiat|radyasyon|nuclear|nükleer|atomik|reactor|reaktör)/i, '☢️'],
  [/\b(light|ışık|photon|foton|beam|ışın|parla|glow|shine|illumin|aydınlat)/i, '💡'],
  [/\b(sound|ses\b|acoustic|frequency|frekans|wave|dalga|titreş|vibrat)/i, '🔊'],
  [/\b(force|kuvvet|pressure|basınç|weight|ağırlık|mass|kütle|momentum)/i, '🏋️'],
  [/\b(fuel|yakıt|petrol|oil\b|coal|kömür|combustion)/i, '⛽'],
  [/\b(renewable|yenilenebilir|sustainable|sürdürülebilir|solar ?panel|turbine|türbin)/i, '♻️'],
  // — Teknoloji —
  [/\b(machine|makine|engine|motor|mechanic|mekanik|device|cihaz|aygıt|apparatus|gear|dişli)/i, '⚙️'],
  [/\b(comput|bilgisayar|digital|sayısal|data|veri|algorit|software|yazılım|kod|code|program)/i, '💻'],
  [/\b(robot|yapay ?zeka|artificial ?intel|otomas|automat|makine ?öğ)/i, '🤖'],
  [/\b(phone|telefon|mobile|mobil|call|arama)/i, '📱'],
  [/\b(network|\bağ\b|internet|web\b|online|çevrimiçi)/i, '🌐'],
  [/\b(camera|kamera|photo|fotoğraf|image|görüntü|resim)/i, '📷'],
  [/\b(screen|ekran|display|göster(ge|im)|monitor)/i, '🖥️'],
  // — İnşaat / nesneler —
  [/\b(build|inşa|construct|yapı\b|structure|bina|architect|mimar|foundation|temel)/i, '🏗️'],
  [/\b(house|\bev\b|home|konut|shelter|barınak|dwelling|mesken)/i, '🏠'],
  [/\b(city|şehir|kent|urban|metropol|town|kasaba)/i, '🏙️'],
  [/\b(bridge|köprü|road|yol\b|highway|otoyol|path|patika|route|güzergah)/i, '🛣️'],
  [/\b(factory|fabrika|industry|sanayi|endüstri|manufactur|üret)/i, '🏭'],
  [/\b(tool|alet|edevat|equipment|ekipman|instrument|araç ?gereç)/i, '🛠️'],
  [/\b(vehicle|araç\b|car\b|araba|otomobil|transport|taşıt|taşım)/i, '🚗'],
  [/\b(ship|gemi|boat|tekne|sail|yelken)/i, '🚢'],
  [/\b(plane|uçak|aircraft|aviation|havacılık|flight|uçuş)/i, '✈️'],
  [/\b(train|tren|railway|demiryolu|ray\b)/i, '🚆'],
  // — Ölçüm / miktar / yön —
  [/\b(measure|ölç|scale|tartı|weigh|metre|meter|length|uzunluk|distance|mesafe)/i, '📏'],
  [/\b(number|sayı|rakam|math|matemat|count|say(mak|ı)|calculat|hesap|arithmetic)/i, '🔢'],
  [/\b(percent|yüzde|oran\b|ratio|rate\b|proportion|orant)/i, '📊'],
  [/\b(increase|artı(r|ş)|arttır|yüksel|rise\b|boost|grow|büyü(me|k)|expand|genişle|augment|çoğal|ascend|yüksel)/i, '📈'],
  [/\b(decrease|azal|düş(me|üş)|reduce|decline|drop\b|diminish|shrink|küçül|lower|gerile|descend)/i, '📉'],
  [/\b(equal|eşit|denk|balance|denge|equival)/i, '⚖️'],
  [/\b(quantity|miktar|amount|nicel|volume|hacim|capacity|kapasite)/i, '📦'],
  [/\b(big|büyük|huge|dev\b|vast|geniş|enormous|massive|kocaman|iri\b|giant|devasa)/i, '🐘'],
  [/\b(small|küçük|tiny|minik|slight|az\b|minor|ufak|micro|minik)/i, '🐜'],
  [/\b(high|yüksek|tall|uzun boy)/i, '⬆️'],
  [/\b(low\b|alçak|düşük)/i, '⬇️'],
  [/\b(full|dolu|complete|tam\b|whole|bütün|entire)/i, '💯'],
  [/\b(empty|boş|vacant|blank)/i, '⭕'],
  // — Zaman —
  [/\b(time|zaman|süre|duration|period|dönem|saat|hour|clock)/i, '⏳'],
  [/\b(fast|hızlı|rapid|quick|swift|çabuk|acele|speed|hız\b|accelerat|hızlan)/i, '🏃'],
  [/\b(slow|yavaş|gradual|kademeli|tedric)/i, '🐌'],
  [/\b(old|eski|ancient|antik|kadim|çağ\b|era|devir|prehistoric|tarih ?öncesi)/i, '🏺'],
  [/\b(new|yeni|modern|çağdaş|recent|güncel|novel|contemporary)/i, '✨'],
  [/\b(future|gelecek|ileride|forthcoming)/i, '🔮'],
  [/\b(begin|başla|start|initi|ilk|onset|kalkış|launch)/i, '🚀'],
  [/\b(end\b|son\b|bit(iş|mek)|finish|final|conclude|terminate|sonlan|bitir)/i, '🏁'],
  // — Eylem / soyut fiiller —
  [/\b(cause|neden|sebep|yol ?aç|lead ?to|result ?in|give ?rise|kaynaklan|stem\b|trigger|tetikle)/i, '➡️'],
  [/\b(prevent|engel|önle|hinder|impede|block|durdur|halt|inhibit|ket ?vur|deter|caydır|hamper)/i, '🚧'],
  [/\b(protect|koru|defend|savun|shield|guard|güvenlik|safe|güvenli|preserve|muhafaza)/i, '🛡️'],
  [/\b(danger|tehlike|risk|threat|tehdit|hazard|peril|jeopard)/i, '⚠️'],
  [/\b(destroy|yık|yok ?et|damage|hasar|ruin|harabe|demolish|devast|tahrip)/i, '💥'],
  [/\b(collapse|çök|göç(mek|ük)|breakdown|çöküş)/i, '🏚️'],
  [/\b(connect|bağla|link|ilişki|relate|associate|ilişkilendir|attach|iliştir|couple)/i, '🔗'],
  [/\b(separate|ayır|böl(mek|ün)|divide|split|parçala|isolate|izole|detach)/i, '✂️'],
  [/\b(change|değiş|alter|modify|transform|dönüş|convert|çevir|shift|vary|adapt|uyarla)/i, '🔄'],
  [/\b(mix|karış|blend|harman|combine|birleş|merge|kaynaş|integrate|bütünleş)/i, '🥣'],
  [/\b(think|düşün|idea|fikir|concept|kavram|theory|kuram|teori|hypothes|varsayım|reason|mantık|mind|zihin|ponder)/i, '💭'],
  [/\b(know|bil(mek|gi)|aware|farkında|understand|anla(mak|yış)|comprehend|kavra|realize)/i, '🧠'],
  [/\b(learn|öğren|educat|eğitim|teach|öğret|study|ders|okul|school|academ|akadem|student|öğrenci)/i, '🎓'],
  [/\b(book|kitap|read|oku(mak|ma)|text|metin|literat|yazın)/i, '📖'],
  [/\b(write|yaz(mak|ı)|record|kayıt|document|belge|note|not ?al|report|rapor|register)/i, '✍️'],
  [/\b(speak|konuş|say\b|söyle|tell|anlat|language|dil\b|voice|ses ?çıkar|utter|dile getir)/i, '🗣️'],
  [/\b(discover|keşf|find\b|bul(mak|gu)|detect|sapta|reveal|ortaya ?çıkar|uncover|açığa)/i, '🔍'],
  [/\b(research|araştır|experiment|deney|test\b|inceleme|analiz|analys|investigat|survey|etüt)/i, '🔬'],
  [/\b(observe|gözlem|watch|izle|monitor|takip|göz ?at)/i, '👀'],
  [/\b(predict|tahmin|forecast|öngör|foresee|anticipate|bekle|kestir)/i, '🔮'],
  [/\b(prove|kanıt|ispat|evidence|delil|demonstrate|göster|verify|doğrula|confirm|teyit)/i, '✅'],
  [/\b(compare|karşılaştır|contrast|kıyas|mukayese)/i, '⚖️'],
  [/\b(describe|betimle|tanımla|define|açıkla|explain|izah|illustrate|resmet)/i, '📝'],
  [/\b(create|yarat|oluştur|produce|üret|generate|meydana ?getir|form\b|make\b|craft|imal)/i, '🏭'],
  [/\b(provide|sağla|sun\b|supply|tedarik|temin|offer|öner|furnish|karşıla)/i, '🎁'],
  [/\b(collect|topla|gather|derle|accumulate|birik|amass|yığ)/i, '🧺'],
  [/\b(spread|yayıl|yay(mak|gın)|distribute|dağıt|disperse|saç(mak|ıl)|scatter)/i, '🌐'],
  [/\b(absorb|emme|em(mek)|soak|çek(mek)|içine ?al|uptake)/i, '🧽'],
  [/\b(release|salıver|serbest ?bırak|emit|yay(mak)|discharge|boşalt|give ?off|çıkar)/i, '💨'],
  [/\b(move|hareket|göç|migrat|travel|seyahat|journey|yolcu|shift|kımılda)/i, '🚶'],
  [/\b(fly|uç(mak|uş)|flight|kanatlan|soar|süzül)/i, '🕊️'],
  [/\b(fall|düş(mek)|drop|dök(ül)|plunge|dal(mak))/i, '🪂'],
  [/\b(support|destek|yardım|aid\b|assist|facilit|kolaylaş|help|back ?up|takviye)/i, '🤝'],
  [/\b(fight|savaş|mücadele|combat|struggle|conflict|çatışma|battle|war\b|harp)/i, '⚔️'],
  [/\b(win|kazan|victory|zafer|success|başarı|achieve|triumph|galip)/i, '🏆'],
  [/\b(lose|kaybet|fail|başarısız|defeat|yenil(gi|mek)|loss|kayıp)/i, '❌'],
  [/\b(goal|amaç|hedef|aim\b|target|purpose|niyet|objective|gaye|maksat)/i, '🎯'],
  [/\b(rare|nadir|scarce|kıt\b|az ?bulunur|uncommon|seyrek|precious|değerli)/i, '💎'],
  [/\b(important|önemli|crucial|vital|hayati|essential|significant|önem|critical|kritik|key\b|başlıca)/i, '⭐'],
  [/\b(difficult|zor\b|hard\b|güç\b|challenging|çetin|complex|karmaşık|complicat|intricate)/i, '🧩'],
  [/\b(easy|kolay|simple|basit|effortless|zahmetsiz)/i, '🟢'],
  [/\b(true|doğru|correct|gerçek|accurate|isabetli|precise|kesin)/i, '✔️'],
  [/\b(false|yanlış|wrong|hatalı|incorrect|error|hata\b|mistake)/i, '❎'],
  [/\b(similar|benzer|alike|aynı|identical|özdeş|resembl|andırır)/i, '👯'],
  [/\b(different|farklı|distinct|ayrı|diverse|çeşitli|various|muhtelif|unlike)/i, '🔀'],
  [/\b(unique|eşsiz|benzersiz|özgün|original|biricik|distinctive)/i, '🦄'],
  [/\b(strong|güçlü|robust|sağlam|powerful|potent|kuvvetli|dayanıklı|durable)/i, '💪'],
  [/\b(weak|zayıf|fragile|kırılgan|feeble|frail|güçsüz|narin)/i, '🥀'],
  [/\b(clean|temiz|pure|saf\b|arı\b|clear|berrak|net\b)/i, '✨'],
  [/\b(dirty|kirli|pollut|kirlilik|contaminat|bulaşık|foul|pis\b|toxic|zehir|toksik|poison)/i, '☣️'],
  [/\b(money|para\b|cost|maliyet|econom|ekonomi|trade|ticaret|finance|mali|price|fiyat|wealth|servet|profit|kâr)/i, '💰'],
  [/\b(law|yasa|hukuk|legal|court|mahkeme|right\b|hak\b|rule|kural|regulat|düzenle|policy|politika)/i, '⚖️'],
  [/\b(govern|yönet|hükümet|state\b|devlet|politic|siyaset|authority|otorite|nation|ulus|millet)/i, '🏛️'],
  [/\b(people|insan|human|toplum|society|social|sosyal|popul|nüfus|communit|topluluk|public|kamu)/i, '👥'],
  [/\b(work|çalış|labor|emek|job\b|iş\b|effort|çaba|task|görev|duty|profession|meslek)/i, '🧑‍🔧'],
  [/\b(map|harita|region|bölge|area|alan|location|konum|place\b|yer\b|zone|kuşak|geograph|coğraf)/i, '🗺️'],
  [/\b(develop|geliş|kalkın|advance|ilerle|progress|improve|iyileş|evolve|evrim|grow)/i, '🌱'],
  [/\b(help|yardım|benefit|fayda|yarar|advantage|avantaj|useful|faydalı|beneficial)/i, '👍'],
  [/\b(harm|zarar|hurt|incit|adverse|olumsuz|detriment|negative|negatif|drawback|dezavantaj)/i, '👎'],
]

const POS_EMOJI: Record<string, string> = {
  v: '🎬', n: '📦', adj: '🏷️', adv: '💫', phrasal: '🔗', 'yapı': '🧩',
}

const cache = new Map<string, string>()

/** Kelimeye anlamına uygun emoji döndürür; eşleşme yoksa türüne göre ikon. */
export function emojiFor(en: string, tr: string, pos: string): string {
  const key = en + '|' + pos
  const hit = cache.get(key)
  if (hit) return hit
  const text = (en + ' ' + tr).toLowerCase()
  let em = POS_EMOJI[pos] || '📘'
  for (const [re, e] of RULES) {
    if (re.test(text)) {
      em = e
      break
    }
  }
  cache.set(key, em)
  return em
}
